#!/bin/bash
set +x

# ref
# https://git-scm.com/docs/gitcredentials

CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/git-credential-gmail"

CONFIG_FILE="$CONFIG_DIR/token"
CONFIG_ENV="$CONFIG_DIR/config"

if [ ! -f "$CONFIG_ENV" ]; then
    echo "Error: configuration not found in $CONFIG_ENV" >&2
    exit 1
fi

if [ "$(stat -c %a "$CONFIG_ENV")" != "600" ]; then
    echo "Error: unsafe permissions on $CONFIG_ENV (use chmod 600)" >&2
    exit 1
fi

set -o allexport
source "$CONFIG_ENV"
set +o allexport

: "${CLIENT_ID:?missing CLIENT_ID}"
: "${CLIENT_SECRET:?missing CLIENT_SECRET}"

ADDRESS="127.0.0.1"
PORT=8080

declare -A gmail=(
    [authorization_endpoint]="https://accounts.google.com/o/oauth2/v2/auth" 
    [token_endpoint]="https://oauth2.googleapis.com/token"
    [response_type]="code"
    [scope]="https://mail.google.com/"
    [client_id]="$CLIENT_ID"
    [client_secret]="$CLIENT_SECRET"
)

load_access_token() {
    json=$(curl --fail --silent --request POST \
        --data "code=${gmail[code]}" \
        --data "client_id=${gmail[client_id]}" \
        --data "redirect_uri=${gmail[redirect_uri]}" \
        --data "grant_type=${gmail[grant_type]}" \
        --data "client_secret=${gmail[client_secret]}" \
        "${gmail[token_endpoint]}")

    if ! echo "$json" | jq -e . >/dev/null 2>&1; then
        echo "Error: invalid response from the OAuth server" >&2
        echo "$json" >&2
        exit 1
    fi

    token=$(jq -r '.access_token // empty' <<< "$json")

    if [ -z "$token" ]; then
        echo "Error: error obtaining access_token" >&2
        echo "$json" >&2
        exit 1
    fi

    echo $token
}

get_access_token() {
    if [ ! -s "$CONFIG_FILE" ]; then
        echo "Error: token missing, run authenticate" >&2
        exit 1
    fi

    ACCESS_TOKEN=$(<"$CONFIG_FILE")
    echo $ACCESS_TOKEN
}

auth_url() {
    echo "${gmail[authorization_endpoint]}?response_type=${gmail[response_type]}&scope=${gmail[scope]}&redirect_uri=${gmail[redirect_uri]}&client_id=${gmail[client_id]}"
}

auth_code() {
    local external="$1"

    local url=$(auth_url)

    if [ "${external}" -eq 1 ]; then
        xdg-open "$url" &
        echo "awaiting authorization in $ADDRESS:$PORT..." >&2

        coproc NC { timeout 240 nc -l -p "$PORT"; }
        
        INPUT_FD=${NC[0]}
        OUTPUT_FD=${NC[1]}

        read -u "$INPUT_FD" request_line
        code=$(echo "$request_line" | grep -o 'code=[^& ]*' | cut -d= -f2)

        while read -u "$INPUT_FD" line && [ "$line" != $'\r' ]; do :; done

        BODY='
        <html>
        <body>
            <p>Authorized! You can close.</p>
            <script>
                window.close();
            </script>
        </body>
        </html>
        '
        LEN=${#BODY}

        {
            echo -e "HTTP/1.1 200 OK\r"
            echo -e "Content-Type: text/html; charset=utf-8\r"
            echo -e "Content-Length: $LEN\r"
            echo -e "Connection: close\r"
            echo -e "\r"
            echo -e "$BODY"
        } >&"$OUTPUT_FD"

        kill "$COPROC_PID" 2>/dev/null
    else
        # TODO: display QR code in terminal and link
        read -p "Paste the authorization code here: " code
    fi

    if [ -z "$code" ]; then
        echo "Error: code not received" >&2
        exit 1
    fi

    echo $code
}

authenticate() {
    local external=0
    local args=()

    OPTIONS=$(getopt -o e --long external -- "$@")
    eval set -- "$OPTIONS"

    while true; do
        case "$1" in
            -e|--external) external=1; shift ;;
            --) shift; break ;;
            *) echo "unknown option: $1"; exit 1 ;;
        esac
    done

    args=("$@")

    if [ "${external}" -eq 1 ]; then
        gmail[redirect_uri]="http://$ADDRESS:$PORT"
    else
        gmail[redirect_uri]="urn:ietf:wg:oauth:2.0:oob"
    fi

    code=$(auth_code "$external")

    gmail[code]="$code"
    gmail[grant_type]="authorization_code"

    token=$(load_access_token)

    umask 077
    printf '%s' "$token" > "$CONFIG_FILE"
    chmod 600 "$CONFIG_FILE"
}

get() {
    echo "password=$(get_access_token)"
}

store() { 
    authenticate --external
}

erase() {
    echo "clearing file with access_token"
    rm -f "$CONFIG_FILE"
}

help() {
    cat << EOF
git-credential-gmail

WARNING
    This tool is intended for development and testing purposes only.
    It is not production-ready and may have security limitations.

    For security reasons, it is recommended to run the 'erase' command after use
    to remove stored credentials/tokens.

DESCRIPTION
    Git credential helper for Gmail using OAuth2 (OAUTHBEARER).

    This tool retrieves and stores an access_token used for authentication with
    Gmail SMTP via Git send-email.

DEPENDENCIES
    perl -MCPAN -e 'install Authen::SASL::Perl::OAUTHBEARER'
    or
    perl -MAuthen::SASL::Perl::OAUTHBEARER -e ''

INSTALLATION
    install -D -m0755 git-credential-gmail /usr/bin/git-credential-gmail

USAGE
    git credential-gmail authenticate --external
    git credential-gmail get
    git credential-gmail store
    git credential-gmail erase

CONFIGURATION
    Create a config file with:
        CLIENT_ID="xxxxx.apps.googleusercontent.com"
        CLIENT_SECRET="xxxxx"

    Git config example:
        [credential "smtp://smtp.gmail.com:465"]
            helper = gmail
        [sendemail]
            smtpEncryption = ssl
            smtpServer = smtp.gmail.com
            smtpUser = <USER>
            smtpServerPort = 465
            smtpAuth = OAUTHBEARER

EOF
}

declare -A COMMANDS=(
    [authenticate]=authenticate
    [get]=get
    [store]=store
    [erase]=erase
    [help]=help
)

cmd="${1:-help}"
shift || true

mkdir -p "$CONFIG_DIR"
chmod 700 "$CONFIG_DIR"

if [[ -n "${COMMANDS[$cmd]}" ]]; then
    "${COMMANDS[$cmd]}" "$@"
else
    help
    exit 1
fi

exit 0